### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by RGBmarya** [RGBmarya/DISH#1]
Hello! I hope you are having a great week. I had a few questions regarding the project. Firstly, in send_request.py, we are returning "requests.get(url, params=params)." However, the URL has never defined anywhere in this file or the others, so is there a way to begin with the path "https://api.edamam.com/search"? Additionally, in parse_json.py, we are, given a response object, separating the individual elements of the json for display and printing the necessary elements from the parsed json request to the user. I was wondering how the response object from send_request.py is utilized here or if there is something that I must do to make sure the response from the API request is properly parsed. Overall, I am struggling a little bit to figure out what I must do in the project, so any help would be greatly appreciated. Thank you very much and have a great rest of your week!

**Comment by c4llmeco4ch** [comment]
> Firstly, in send_request.py, we are returning "requests.get(url, params=params)." However, the URL has never defined anywhere in this file or the others, so is there a way to begin with the path "https://api.edamam.com/search"?

For this part, we'll likely have it passed in from some sort of a runner/main function. This way, if there is an issue with the URL being changed, we can offer different ways to fix that as a command line option (idk, -t/--target changes the target URL in case they want to do food searches instead of recipe searches...?).

> Additionally, in parse_json.py, we are, given a response object, separating the individual elements of the json for display and printing the necessary elements from the parsed json request to the user. I was wondering how the response object from send_request.py is utilized here or if there is something that I must do to make sure the response from the API request is properly parsed. 

So, we will take in the request from send_request.send_request, use [Response.json() seen here](https://2.python-requests.org/en/master/user/quickstart/#json-response-content) to pull the json (given as a dictionary of keys and values), then take the "recipe" key (try running a request on Postman if you need to see what an API response looks like) and pull it apart to figure out the steps and ingredients.

For now, what I would focus on is doing your best with parse_json.extract_recipies(). Assume we have a valid Response received from send_request(), pull the recipes from the json and store them all in a list (a "cookbook", if you will). If you're feeling adventurous, look at the Postman responses and see if you can start thinking about how we will determine what is the most ideal recipe. 

I get this is a lot. We're exploring uncharted territory, so it's completely reasonable for you to feel like you are not understanding it all. Don't worry. We will get there :) you're doing great. You're an awesome student to have and we'll take it piece by piece.
